version: '3.1'

services:

  app:
    image: krayseer/gpt:1.1
    container_name: gpt
    ports:
      - '6677:8080'
    environment:
      - URL_CHROME=http://selenium:4444/wd/hub
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - '4444:4444'